all:
	gcc -Wall -O2 -lm -o random_walk random_walk.c
upload:
	scp -r ../2_HW20170930 st15307110218@10.40.9.67:Homework/
download:
	scp -r st15307110218@10.40.9.67:Homework/HW20170930 ../from_server
clean:
	rm random_walk