all:
	gcc -Wall -O2 -lm -o monte_carlo_walk monte_carlo_walk.c
upload:
	scp -r ../3_HW20171013 st15307110218@10.40.9.67:Homework/
download:
	scp -r st15307110218@10.40.9.67:Homework/HW20171013 ../from_server
clean:
	rm monte_carlo_walk